import '../models/transaction.dart';

/// Parser for Meezan Bank account statements generated by Apache FOP.
///
/// Input contract: after the pdf_text offset fix, each PDF page comes out
/// as one long line with cells glued together (no separators) —
/// `Booking DateDescriptionCreditDebitAvailable Balance` as the header
/// marker, then rows like
/// `31 Mar 2026Raast P2P Fund transfer to SOMEONE PK18TMFBxxxx4709...260331055456- PKR700.00PKR27,937.02`,
/// rows glued date-to-balance (`...PKR27,937.0202 Apr 2026...`), and a
/// `<pageno>30 Sep 2026, 14:17` footer at the end of each page.
///
/// Algorithm (validated: 234/234 rows, 0 balance mismatches on a real
/// 6-month statement):
/// - per page: find the header marker, discard everything before it
///   (kills the page-1 header block whose From/To dates would false-match);
///   pages without the marker are skipped with a warning.
/// - split the page into row chunks on the balance→next-date boundary;
///   the final chunk runs to the page end (footer included).
/// - per chunk: date at the start, then the first signed `± PKR <amt>`
///   is the transaction amount, the text between is the description,
///   the next unsigned `PKR <amt>` is the running balance, and the tail
///   must be empty or the page footer.
/// - balances self-validate as a chain (prev ± amount == balance).
class MeezanParser {
  // Month names; FOP writes "Mar", "Sep" etc. The [a-z]* tail also
  // accepts full names ("March") if a statement ever uses them.
  static const _mon =
      r'(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*';
  // Strict amount: 1-3 digits, comma groups, exactly 2 decimals.
  static const _amt = r'\d{1,3}(?:,\d{3})*\.\d{2}';
  // Date with NO word boundaries on either side — dates sit glued
  // between the previous row's balance and the description.
  static const _dateSrc = r'(\d{1,2}) (' + _mon + r') (\d{4})';

  static final _dateRe = RegExp(_dateSrc);
  static final _markRe = RegExp(
      r'Booking\s*Date\s*Description\s*Credit\s*Debit\s*Available\s*Balance');
  // Row boundary: a balance immediately followed by the next row's date.
  // (Matched in two steps — Dart's Match exposes no per-group offsets —
  //  which is equivalent to the single regex PKR(AMT)(DATE).)
  static final _pkrAmtRe = RegExp('PKR' + _amt);
  static final _signedRe = RegExp(r'([+-])\s*PKR\s*(' + _amt + r')');
  static final _ubalRe = RegExp(r'PKR\s*(' + _amt + r')');
  // Page footer: page number glued to a timestamp, at the page end.
  static final _footerTailRe =
      RegExp(r'^\d*\d{1,2} (' + _mon + r') \d{4}, \d{1,2}:\d{2}$');

  static const _months = <String, int>{
    'jan': 1, 'feb': 2, 'mar': 3, 'apr': 4, 'may': 5, 'jun': 6,
    'jul': 7, 'aug': 8, 'sep': 9, 'oct': 10, 'nov': 11, 'dec': 12,
  };

  /// True when the extracted text looks like a Meezan FOP statement.
  static bool looksLike(String text) => _markRe.hasMatch(text);

  static MeezanStatement parse(String text) {
    final warnings = <String>[];
    final rows = <MeezanRow>[];
    MeezanHeader? header;
    var firstPage = true;

    for (final line in text.split('\n')) {
      if (line.trim().isEmpty) continue;
      final mark = _markRe.firstMatch(line);
      if (mark == null) {
        warnings.add('Skipped a page without the statement header.');
        continue;
      }
      if (firstPage) {
        header = _parseHeader(line.substring(0, mark.start));
        firstPage = false;
      }
      _parsePage(line.substring(mark.end), rows, warnings);
    }

    // Self-validation: the running balances must chain
    // (prev ± amount == balance). Warnings only — never crash.
    double? prev = header?.openingBalance;
    for (var i = 0; i < rows.length; i++) {
      final r = rows[i];
      if (prev != null) {
        final expected = prev + (r.kind == TxnKind.receive ? r.amount : -r.amount);
        if ((expected - r.balance).abs() > 0.011) {
          warnings.add('Balance check failed after "${r.description}": '
              'expected ${_fmt(expected)}, found ${_fmt(r.balance)}.');
        }
      }
      prev = r.balance;
    }

    return MeezanStatement(
      rows: rows,
      header: header ?? const MeezanHeader(),
      warnings: warnings,
    );
  }

  static void _parsePage(
      String page, List<MeezanRow> rows, List<String> warnings) {
    // Split into row chunks on the balance→next-date boundary. Chunk i
    // ends where the next row's date starts; the final chunk runs to the
    // page end (footer included).
    final bounds = <int>[];
    for (final m in _pkrAmtRe.allMatches(page)) {
      if (_dateRe.matchAsPrefix(page, m.end) != null) bounds.add(m.end);
    }
    var start = 0;
    for (var b = 0; b <= bounds.length; b++) {
      final end = b < bounds.length ? bounds[b] : page.length;
      final chunk = page.substring(start, end);
      start = end;
      if (chunk.trim().isEmpty) continue;
      final row = _parseChunk(chunk, warnings);
      if (row != null) rows.add(row);
    }
  }

  static MeezanRow? _parseChunk(String chunk, List<String> warnings) {
    // The date must lead the chunk. Tolerate stray whitespace; anything
    // else gets a forward scan with a warning. Never parse dateless.
    var body = chunk;
    var dateM = _dateRe.matchAsPrefix(body);
    if (dateM == null) {
      final trimmed = body.trimLeft();
      dateM = _dateRe.matchAsPrefix(trimmed);
      if (dateM != null) {
        body = trimmed;
      } else {
        dateM = _dateRe.firstMatch(body);
        if (dateM == null) {
          warnings.add('Skipped a row with no date: "${_short(chunk)}".');
          return null;
        }
        warnings.add(
            'Row did not start with a date; scanned forward: "${_short(chunk)}".');
        body = body.substring(dateM.start);
        dateM = _dateRe.matchAsPrefix(body);
      }
    }
    final dateMatch = dateM!;
    final date = DateTime(
      int.parse(dateMatch.group(3)!),
      _months[dateMatch.group(2)!.toLowerCase().substring(0, 3)]!,
      int.parse(dateMatch.group(1)!),
    );

    final afterDate = body.substring(dateMatch.end);
    // The first signed PKR amount after the date is the transaction
    // amount. (Validated on real data: no row carries a signed PKR
    // amount inside its description text, so the first match is it.)
    final signedM = _signedRe.firstMatch(afterDate);
    if (signedM == null) {
      warnings.add('Skipped a row with no amount: "${_short(chunk)}".');
      return null;
    }
    final isOut = signedM.group(1) == '-';
    final amount = _parseAmt(signedM.group(2)!);
    final descRaw = afterDate.substring(0, signedM.start);

    final afterAmt = afterDate.substring(signedM.end);
    final balM = _ubalRe.firstMatch(afterAmt);
    if (balM == null) {
      warnings.add('Skipped a row with no balance: "${_short(chunk)}".');
      return null;
    }
    final balance = _parseAmt(balM.group(1)!);

    // Do NOT pre-strip the footer: naive stripping eats balance digits.
    // The tail after the balance must be empty or the page footer.
    final tail = afterAmt.substring(balM.end);
    if (tail.isNotEmpty && !_footerTailRe.hasMatch(tail)) {
      warnings.add('Unexpected text after a row balance: "${_short(tail)}".');
    }

    final description = _cleanDescription(descRaw);
    final kind = isOut ? TxnKind.spend : TxnKind.receive;
    return MeezanRow(
      date: date,
      description: description,
      amount: amount,
      kind: kind,
      balance: balance,
      reference: _reference(descRaw, amount),
      suggestedPurpose: _suggestPurpose(description.toLowerCase(), kind),
    );
  }

  /// Page-1 header block, best-effort: account title/number, period,
  /// opening/closing balances. Everything is nullable — a missing piece
  /// never fails the parse.
  static MeezanHeader _parseHeader(String head) {
    String? grab(Pattern p) {
      final m = (p is RegExp ? p : RegExp(p as String)).firstMatch(head);
      return m?.group(1)?.trim();
    }

    DateTime? grabDate(String label) {
      final m = RegExp(label + _dateSrc).firstMatch(head);
      if (m == null) return null;
      final month = _months[m.group(2)!.toLowerCase().substring(0, 3)];
      if (month == null) return null;
      return DateTime(
          int.parse(m.group(3)!), month, int.parse(m.group(1)!));
    }

    double? grabAmt(String label) {
      final s = grab(RegExp(label + r'PKR\s*(' + _amt + r')'));
      return s == null ? null : _parseAmt(s);
    }

    return MeezanHeader(
      accountTitle: grab(RegExp(r'Account Title(.+?)Account Number')),
      accountNumber: grab(RegExp(r'Account Number(\d+)')),
      from: grabDate('From Date'),
      to: grabDate('To Date'),
      openingBalance: grabAmt('Opening Balance'),
      closingBalance: grabAmt('Closing Balance'),
    );
  }

  /// Description cleanup: deterministic, so duplicate detection on the
  /// merchant text stays stable.
  static String _cleanDescription(String raw) {
    // FOP renders an arrow glyph as a raw '>' byte.
    var s = raw.replaceAll('>', ' → ');
    // Insert a space on lowercase→Uppercase boundaries
    // ("WithdrawalHAFIZABAD" → "Withdrawal HAFIZABAD").
    s = s.replaceAllMapped(
        RegExp(r'([a-z])([A-Z])'), (m) => '${m[1]} ${m[2]}');
    s = s.replaceAll(RegExp(r'\s+'), ' ').trim();
    return s;
  }

  /// Bank reference: prefer the long Raast RRN; else a STAN qualified
  /// with the amount (`STAN<digits>:<amount>`). Bare STANs repeat across
  /// fee+transfer pairs, and YaadDb.findDuplicate matches on the
  /// reference alone — an unqualified STAN would false-drop rows.
  static String? _reference(String descRaw, double amount) {
    final rrn = RegExp(r'[A-Z]{2,10}\d{8,}').firstMatch(descRaw);
    if (rrn != null) return rrn.group(0);
    final stan = RegExp(r'STAN\s*\(?(\d+)\)?').firstMatch(descRaw);
    if (stan != null) {
      return 'STAN${stan.group(1)}:${amount.toStringAsFixed(2)}';
    }
    return null;
  }

  /// Keyword → purpose suggestion. Person-to-person transfers deliberately
  /// map to uncategorized/other_in — never guess gift vs loan; the user
  /// marks Udhaar in the preview.
  static String? _suggestPurpose(String descLower, TxnKind kind) {
    bool hasAny(List<String> kws) =>
        kws.any((k) => descLower.contains(k));

    if (kind == TxnKind.receive) {
      if (hasAny(const ['adjustment reversal', 'reversal'])) return 'refund';
      if (hasAny(const [
        'raast p2p fund transfer',
        'money transferred to',
        'money received from',
        'remittance from',
      ])) {
        return 'other_in';
      }
      return null;
    }
    if (hasAny(const [
      'online purchase',
      'daraz',
      'bata',
      'kayseria',
      'metapay',
      'shoe',
      'wear',
      'mall',
    ])) {
      return 'shopping';
    }
    if (hasAny(const [
      'sajji',
      'bakers',
      'pizza',
      'food',
      'churn station',
      'restaurant',
    ])) {
      return 'food';
    }
    if (hasAny(const ['superstore', 'mart', 'karyana'])) return 'groceries';
    if (hasAny(const ['airblue', 'air blue', 'pia', 'autos', 'motors'])) {
      return 'transport';
    }
    if (hasAny(const [
      'raast p2p fund transfer',
      'money transferred to',
      'money received from',
      'remittance from',
      'atm cash withdrawal',
      'bank charges',
      'charges taxes plus',
      '1-link fee',
      'duplicate statement',
      'fed',
    ])) {
      return 'uncategorized';
    }
    return null;
  }

  static double _parseAmt(String s) =>
      double.parse(s.replaceAll(',', ''));

  static String _fmt(double v) => v.toStringAsFixed(2);

  static String _short(String s) =>
      s.length <= 60 ? s : '${s.substring(0, 60)}…';
}

/// One parsed Meezan statement row.
class MeezanRow {
  final DateTime date;
  final String description;
  final double amount; // always positive
  final TxnKind kind; // spend or receive
  final double balance; // available balance after this row
  final String? reference;
  final String? suggestedPurpose;

  const MeezanRow({
    required this.date,
    required this.description,
    required this.amount,
    required this.kind,
    required this.balance,
    this.reference,
    this.suggestedPurpose,
  });
}

/// Page-1 header metadata, for the preview subtitle.
class MeezanHeader {
  final String? accountTitle;
  final String? accountNumber;
  final DateTime? from;
  final DateTime? to;
  final double? openingBalance;
  final double? closingBalance;

  const MeezanHeader({
    this.accountTitle,
    this.accountNumber,
    this.from,
    this.to,
    this.openingBalance,
    this.closingBalance,
  });
}

class MeezanStatement {
  final List<MeezanRow> rows;
  final MeezanHeader header;
  final List<String> warnings;

  const MeezanStatement({
    required this.rows,
    required this.header,
    this.warnings = const [],
  });
}
